version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:mypass@db:5432/weatherdb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=weatherdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
    networks:
      - app-network
    depends_on:
      - db
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]


  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
